# Generated by Django 4.2.2 on 2023-06-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.URLField(blank=True)),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
