# Generated by Django 4.2.1 on 2023-06-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posts', to='user.post'),
        ),
    ]
